services:
  gotify:
    image: gotify/server:latest
    container_name: gotify
    hostname: gotify
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Europe/Berlin
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gotify.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.gotify.entrypoints=websecure"
      - "traefik.http.routers.gotify.tls.certresolver=dnsresolver"
      - "traefik.http.routers.gotify.tls.domains[0].main=${DOMAIN}"

networks:
  proxy:
    external: true