#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

echo "=== Auto Backup Setup ==="

# Ask for config
read -rp "Enter USB device path (e.g., /dev/sda1): " USB_DEVICE
read -rp "Enter USB mount point (e.g., /mnt/backup_usb): " BACKUP_MOUNT
read -rp "Enter source path to back up (e.g., /mnt/ssd/): " BACKUP_SRC
read -rp "Enter Borg repo path (default: /mnt/backup_usb/borgrepo): " BORG_REPO
BORG_REPO=${BORG_REPO:-/mnt/backup_usb/borgrepo}
read -rp "Enter Borg passphrase: " BORG_PASSPHRASE
read -rp "Enter daily backup time (default: 02:00:00): " BACKUP_TIME
BACKUP_TIME=${BACKUP_TIME:-02:00:00}
read -rp "Enter systemd service name (default: auto-backup): " SERVICE_NAME
SERVICE_NAME=${SERVICE_NAME:-auto-backup}

# Save to .env
cat > "$ENV_FILE" <<EOF
# auto_backup/.env (generated by setup)

USB_DEVICE=$USB_DEVICE
BACKUP_USB_LABEL=BACKUP_USB
BACKUP_MOUNT=$BACKUP_MOUNT
BACKUP_SRC=$BACKUP_SRC
BORG_REPO=$BORG_REPO
BORG_PASSPHRASE=$BORG_PASSPHRASE
LOG_FILE=$SCRIPT_DIR/backup.log
BACKUP_TIME=$BACKUP_TIME
SERVICE_NAME=$SERVICE_NAME
EOF

echo "[INFO] Configuration saved to $ENV_FILE"

# Create systemd service and timer
SERVICE_FILE="/etc/systemd/system/$SERVICE_NAME.service"
TIMER_FILE="/etc/systemd/system/$SERVICE_NAME.timer"

sudo tee "$SERVICE_FILE" > /dev/null <<EOF
[Unit]
Description=Automatic Borg Backup

[Service]
Type=oneshot
EnvironmentFile=$ENV_FILE
ExecStart=$SCRIPT_DIR/backup_start.sh
EOF

sudo tee "$TIMER_FILE" > /dev/null <<EOF
[Unit]
Description=Run automatic backup daily at $BACKUP_TIME

[Timer]
OnCalendar=*-*-* $BACKUP_TIME
Persistent=true

[Install]
WantedBy=timers.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable --now "$SERVICE_NAME.timer"

echo "[INFO] Systemd service and timer installed and started."
echo "Setup complete. Logs will be written to $SCRIPT_DIR/backup.log"
echo "You can check the status with: sudo systemctl status $SERVICE_NAME.timer"
echo "To see logs: journalctl -u $SERVICE_NAME.service"
echo "To manually run the backup: sudo systemctl start $SERVICE_NAME.service"
echo "To remove this setup run the cleanup script: $SCRIPT_DIR/backup_remove.sh"
echo "========================="
