services:
  adguard_home:
    image: adguard/adguardhome:latest
    container_name: adguard_home
    hostname: adguard_home
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    environment:
      - TZ=Europe/Berlin
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard_home.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.adguard_home.entrypoints=websecure"
      - "traefik.http.routers.adguard_home.tls.certresolver=dnsresolver"
      - "traefik.http.routers.adguard_home.tls.domains[0].main=${DOMAIN}"

networks:
  proxy:
    external: true
