services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    hostname: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"  # Default MongoDB port
    networks:
      - proxy
    environment:
      - MONGO_INITDB_ROOT_USERNAME=joshuawiebe
      - MONGO_INITDB_ROOT_PASSWORD=${PASSWORD}
    volumes:
      - ./data:/data/db

networks:
  proxy:
    external: true
