services:
  zoraxy:
    image: zoraxydocker/zoraxy:latest
    container_name: zoraxy
    hostname: zoraxy
    restart: unless-stopped
    ports:
      - "80:80"       # HTTP (Zoraxy Reverse Proxy)
      - "443:443"     # HTTPS (Zoraxy Reverse Proxy)
      - "8000:8000"   # Zoraxy Admin UI
      - "53:53/tcp"   # AdGuard DNS (TCP)
      - "53:53/udp"   # AdGuard DNS (UDP)
      - "27017:27017" # MongoDB (Default)
    volumes:
      - ./config/:/opt/zoraxy/config/
      - ./plugin/:/opt/zoraxy/plugin/
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime
    environment:
      FASTGEOIP: "true"
    networks:
      - proxy

networks:
  proxy:
    external: true
