services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    hostname: nextcloud
    restart: always
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - PHP_OPCACHE_MEMORY_CONSUMPTION=256
    networks:
      - proxy
    depends_on:
      - redis
      - db

  cron:
   image: nextcloud
   container_name: nextcloud_cron
   restart: always
   volumes:
     - ./nextcloud:/var/www/html
   entrypoint: /cron.sh
   depends_on:
     - nextcloud

  db:
    image: mariadb:10.11
    restart: always
    command: --transaction-isolation=READ-COMMITTED
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - proxy

  redis:
    image: redis:alpine
    restart: always
    networks:
      - proxy

networks:
  proxy:
    external: true
