services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    hostname: nextcloud
    restart: always
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - PHP_OPCACHE_MEMORY_CONSUMPTION=256
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=dnsresolver"
      - "traefik.http.routers.nextcloud.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.middlewares.nextcloud-headers.headers.STSSeconds=31536000"
      - "traefik.http.middlewares.nextcloud-headers.headers.STSIncludeSubdomains=true"
      - "traefik.http.middlewares.nextcloud-headers.headers.STSPreload=true"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-headers@docker"
    depends_on:
      - redis
      - db

  cron:
    image: nextcloud
    container_name: nextcloud_cron
    hostname: nextcloud_cron
    restart: always
    volumes:
      - ./nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - nextcloud
    networks:
      - proxy

  db:
    image: mariadb:10.11
    container_name: db
    hostname: db
    restart: always
    command: --transaction-isolation=READ-COMMITTED
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - proxy

  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    restart: always
    networks:
      - proxy

networks:
  proxy:
    external: true